### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by Climber-Chinese** [SouthernYard/QuantWorld#1]
最近一年从事区块链方面开发(支付系统)，所以也接触了数字货币，最近刚好准备开发一个交易机器人，对该项目比较感兴趣，希望能做出贡献，方便留一下vx联系方式吗？

**Comment by SouthernYard** [comment]
@Climber-Chinese , 因为该项目存在一些已知的问题, 目前已经不再进行开发了, 只是处于维护的状态, 同时我也在针对这些问题做一些更大的升级和架构重构, 目前还在私有repo开发. 对于交易方面的问题, 我们也可以交流一下, 方便的话可以加我 vx:1152289272
