### ISSUE TITLE
太多bug了!!!!!

### ISSUE THREAD

**Issue by cd13719791** [SouthernYard/QuantWorld#2]
接入进来各种bug,修完一个又一个.背书做那么漂亮,瞎耽误时间

**Comment by SouthernYard** [comment]
这个开源版本是原版本剥离核心代码后开源的, 确实有一些bug, 我也不准备修了, 后续的功能我也不会迭代, 目前版本你可以作为一种参考. 也因为系统本身存在一些致命问题(参考这篇文章: [Xronos: 架构设计-1](https://www.itnote.tech/2020/09/08/Xronos%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1-1/)), 目前在开发新一款高性能系统.
